"""Manuscript tables generated ONLY from result files (no hand-typed numbers). Output: manuscript/tables/*.tex
  tab_taxonomy.tex        results/phase2i/p2i_taxonomy.csv
  tab_constructions.tex   results/phase2i/p2i_constructions.csv
  tab_structural_<tau>.tex results/final/structural/structural_tradeoff.csv
  tab_gate_identity.tex   results/final/structural/gated_vs_ungated_identity.csv
  macros.tex              scalar numbers quoted in the text (\\newcommand), each with its source file
"""
from pathlib import Path

import pandas as pd
import yaml

R = Path(__file__).resolve().parents[1]
T = R / "manuscript/tables"
CFG = yaml.safe_load((R / "configs/final_v1.yaml").read_text())
INV = {k: d for d, k in CFG["display_names"].items()}


def f(x, d=1):
    return f"{x:,.{d}f}"


def tex_class(c):
    return "\\texttt{" + c.replace("_", "\\_") + "}"


def main():
    T.mkdir(parents=True, exist_ok=True)
    tx = pd.read_csv(R / "results/phase2i/p2i_taxonomy.csv", header=None, index_col=0, skiprows=1)[1]
    chem = yaml.safe_load((R / "configs/chemistry_v1.yaml").read_text())
    rows = []
    for t in chem["protection"]["taxonomy"]:
        n = int(tx[f"class_{t['class']}"])
        rows.append(f"{tex_class(t['class'])} & {t['pair']} & {'yes' if t['protected'] else 'no'} & {t['rule'].replace('_', ' ')} & {n:,} & {100 * n / tx['instances']:.2f} \\\\")
    (T / "tab_taxonomy.tex").write_text("\n".join(rows) + "\n\\bottomrule\n")

    C = pd.read_csv(R / "results/phase2i/p2i_constructions.csv")
    rows = [f"{r.view} & {f(r.mean_instances)} & {f(r.pct_of_original)} & {f(100 * r.connected_frac)} & {f(r.retained_covalent_radius_pct, 2)} & "
            f"{f(r.retained_metal_ligand_pct, 2)} & {f(r.retained_metal_metal_crystalnn_pct, 1)} \\\\" for r in C.itertuples()]
    (T / "tab_constructions.tex").write_text("\n".join(rows) + "\n\\bottomrule\n")

    S = pd.read_csv(R / "results/final/structural/structural_tradeoff.csv", index_col=0)
    for tau in (0.2, 0.5):
        sub = S[S.index.str.endswith(f"@{tau}")]
        rows = []
        for v, r in sub.iterrows():
            rows.append(f"{r.display_name.split('@')[0]} & {'yes' if r.gated else 'no'} & {f(r.protected_retention_tol040_pct, 3)} & "
                        f"{int(r.structures_losing_protected_tol040):,} & {f(r.shell_complete_r3_0_pct if 'shell_complete_r3_0_pct' in r else r['shell_complete_r3.0_pct'])} & "
                        f"{f(r.loss_frac_metal, 2)} & {f(r.loss_frac_H, 2)} & {f(r.removed_H_involving_pct)} & {f(r.hb_candidate_retention_pct)} \\\\")
        (T / f"tab_structural_{str(tau).replace('.', 'p')}.tex").write_text("\n".join(rows) + "\n\\bottomrule\n")

    G = pd.read_csv(R / "results/final/structural/gated_vs_ungated_identity.csv")
    name = {"ChemSPAR_v2": "Gravity", "Distance_Chem": "Distance", "Random_Chem": "Random", "BHS_edge_min": "BHS-derived"}
    rows = [f"{name[r.gated]} & {r.tau} & {r.structures_differing:,} & {r.instances_differing:,} & {r.mean_jaccard:.4f} \\\\" for r in G.itertuples()]
    (T / "tab_gate_identity.tex").write_text("\n".join(rows) + "\n\\bottomrule\n")

    A = pd.read_csv(R / "results/final/audit/rejections_tau0.5.csv", index_col=0)
    prot = [c for c in A.columns if c.startswith("rej::protected")]
    rows = []
    for k in ["ChemSPAR-v2", "Distance-Chem", "Random-Chem", "BHS-edge-min", "Random", "BHS-edge-min-noGate"]:
        r = A.loc[k]
        rows.append(f"{INV[k]} & {int(r[prot].sum()):,} & {int(r['rej::degree']):,} & {int(r['rej::connectivity']):,} & {int(r.removed):,} \\\\")
    (T / "tab_audit_rejections.tex").write_text("\n".join(rows) + "\n\\bottomrule\n")
    AS = pd.read_csv(R / "results/final/audit/audit_storage.csv")

    coh = pd.read_csv(R / "data/cohort_5000_v1.csv")
    m = {"NCohort": f"{len(coh):,}", "NTrain": f"{(coh.split == 'train').sum():,}", "NVal": f"{(coh.split == 'val').sum():,}",
         "NTest": f"{(coh.split == 'test').sum():,}", "NInstances": f"{int(tx['instances']):,}", "NSelfImage": f"{int(tx['self_image']):,}",
         "NMultiPairs": f"{int(tx['pairs_with_multiple_instances']):,}", "NPairs": f"{int(tx['atom_pairs']):,}",
         "MeanInst": f(C.set_index('view').loc['Original-4.5', 'mean_instances']),
         "NProtected": f"{int(tx['class_covalent_radius'] + tx['class_metal_ligand'] + tx['class_metal_metal_crystalnn']):,}",
         "AuditRowsPerStructure": f(AS.rows_per_structure.mean(), 0), "AuditBytesPerRow": f(AS.parquet_bytes_per_row_all_policies.iloc[0], 1),
         "AuditStructures": f"{int(AS.structures.iloc[0]):,}",
         "PctProtected": f(100 * (tx['class_covalent_radius'] + tx['class_metal_ligand'] + tx['class_metal_metal_crystalnn']) / tx['instances'], 1)}
    (T / "macros.tex").write_text("% generated by scripts/ms_make_tables.py from data/cohort_5000_v1.csv, results/phase2i/*.csv\n" +
                                  "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in m.items()))
    print(m)


if __name__ == "__main__":
    main()
